


development:
  adapter: postgresql
  encoding: unicode
  database: taketwo_development
  pool: 5
  username: taketwo
  password: 2020

test:
  adapter: postgresql
  encoding: unicode
  database: taketwo_test
  pool: 5
  username: taketwo
  password: 2020
